# -*- coding: utf-8 -*-
"""decodelabs 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q2rcmPPBiGB5RYQAh_JuhoyfMApdSik6
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_excel("Dataset for Data Analytics.xlsx")

df.head()

print("Shape of Dataset:")
print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nFirst 5 Rows:")
print(df.head())

df.info()

print(df.isnull().sum())

print("Duplicate Records:", df.duplicated().sum())

print(df.describe())

print(df.mean(numeric_only=True))

print(df.median(numeric_only=True))

print(df["Product"].value_counts())

print(df["PaymentMethod"].value_counts())

print(df["ReferralSource"].value_counts())

df["Date"] = pd.to_datetime(df["Date"])

monthly_orders = df.groupby(df["Date"].dt.month)["OrderID"].count()

monthly_orders.plot(kind="line", marker="o")
plt.title("Monthly Order Trend")
plt.xlabel("Month")
plt.ylabel("Number of Orders")
plt.show()

df[["Quantity","UnitPrice","ItemsInCart","TotalPrice"]].hist(figsize=(12,8))
plt.show()

import seaborn as sns

sns.boxplot(x=df['TotalPrice'])
plt.show()

corr = df[['Quantity','UnitPrice','ItemsInCart','TotalPrice']].corr()

sns.heatmap(corr, annot=True)
plt.show()

print("========== KEY OBSERVATIONS ==========")
print(f"\n1. Dataset contains {df.shape[0]} rows and {df.shape[1]} columns.")
print(f"\n2. Total missing values: {df.isnull().sum().sum()}")
print(f"\n3. Duplicate records found: {df.duplicated().sum()}")
print(f"\n4. Most ordered product: {df['Product'].mode()[0]}")
print(f"\n5. Most used payment method: {df['PaymentMethod'].mode()[0]}")
print(f"\n6. Most common order status: {df['OrderStatus'].mode()[0]}")
print(f"\n7. Average order value: {df['TotalPrice'].mean():.2f}")
print(f"\n8. Maximum order value: {df['TotalPrice'].max():.2f}")
print(f"\n9. Minimum order value: {df['TotalPrice'].min():.2f}")
print(f"\n10. Average quantity ordered: {df['Quantity'].mean():.2f}")